### ISSUE TITLE
Debian issue on Windows 10 2004 (WSL2)

### ISSUE THREAD

**Issue by xurxo1982** [dockette/debian#1]
There is an issue with the Debian image, executed under the last Docker Desktop (version 2.4.0): trying to install any package or even executing an apt-get update, it fails and displays the following message:
`E: Method http has died unexpectedly!

E: Sub-process http received a segmentation fault.`

**Comment by f3l1x** [comment]
Unfortunately I don't use WSL1/2. I can't help you.
